//
//  FUGlyphs.swift
//  FlatUI
//
//  Created by xiaoxiang's m1 mbp on 2023/8/25.
//

import Foundation

struct FUGlyphs{
    static let info_circle = "\u{e600}"
    static let alert_circle = "\u{e601}"
    static let question_circle = "\u{e602}"
    static let check_circle = "\u{e603}"
    static let cross_circle = "\u{e604}"
    static let plus_circle = "\u{e605}"
    static let window = "\u{e606}"
    static let windows = "\u{e607}"
    static let upload = "\u{e608}"
    static let arrow_right = "\u{e609}"
    static let arrow_left = "\u{e60a}"
    static let loop = "\u{e60b}"
    static let cmd = "\u{e60c}"
    static let mic = "\u{e60d}"
    static let export = "\u{e60e}"
    static let heart = "\u{e60f}"
    static let location = "\u{e610}"
    static let plus = "\u{e611}"
    static let check = "\u{e612}"
    static let cross = "\u{e613}"
    static let list = "\u{e614}"
    static let new = "\u{e615}"
    static let video = "\u{e616}"
    static let photo = "\u{e617}"
    static let time = "\u{e618}"
    static let eye = "\u{e619}"
    static let chat = "\u{e61a}"
    static let home = "\u{e61b}"
    static let search = "\u{e61c}"
    static let user = "\u{e61d}"
    static let mail = "\u{e61e}"
    static let lock = "\u{e61f}"
    static let power = "\u{e620}"
    static let star = "\u{e621}"
    static let calendar = "\u{e622}"
    static let gear = "\u{e623}"
    static let bookmark = "\u{e624}"
    static let exit = "\u{e625}"
    static let trash = "\u{e626}"
    static let folder = "\u{e627}"
    static let bubble = "\u{e628}"
    static let calendar_solid = "\u{e629}"
    static let star_2 = "\u{e62a}"
    static let credit_card = "\u{e62b}"
    static let clip = "\u{e62c}"
    static let link = "\u{e62d}"
    static let pause = "\u{e62e}"
    static let play = "\u{e62f}"
    static let volume = "\u{e630}"
    static let mute = "\u{e631}"
    static let resize = "\u{e632}"
    static let tag = "\u{e633}"
    static let document = "\u{e634}"
    static let image = "\u{e635}"
    static let triangle_up = "\u{e636}"
    static let triangle_up_small = "\u{e637}"
    static let triangle_right_large = "\u{e638}"
    static let triangle_left_large = "\u{e639}"
    static let triangle_down = "\u{e63a}"
    static let triangle_down_small = "\u{e63b}"
    static let radio_unchecked = "\u{e63c}"
    static let radio_checked = "\u{e63d}"
    static let checkbox_unchecked = "\u{e63e}"
    static let checkbox_checked = "\u{e63f}"
    static let list_thumbnailed = "\u{e640}"
    static let list_small_thumbnails = "\u{e641}"
    static let list_numbered = "\u{e642}"
    static let list_large_thumbnails = "\u{e643}"
    static let list_columned = "\u{e644}"
    static let list_bulleted = "\u{e645}"
    
    
    // Social media
    static let facebook = "\u{e646}"
    static let youtube = "\u{e647}"
    static let vimeo = "\u{e648}"
    static let twitter = "\u{e649}"
    static let stumbleupon = "\u{e64a}"
    static let spotify = "\u{e64b}"
    static let skype = "\u{e64c}"
    static let pinterest = "\u{e64d}"
    static let path = "\u{e64e}"
    static let linkedin = "\u{e64f}"
    static let google = "\u{e650}"
    static let dribbble = "\u{e651}"
    static let behance = "\u{e652}"
    static let yelp = "\u{e653}"
    static let wordpress = "\u{e654}"
    static let windows_icon = "\u{e655}"
    static let vine = "\u{e656}"
    static let tumblr = "\u{e657}"
    static let paypal = "\u{e658}"
    static let lastfm = "\u{e659}"
    static let instagram = "\u{e65a}"
    static let html5 = "\u{e65b}"
    static let github = "\u{e65c}"
    static let foursquare = "\u{e65d}"
    static let dropbox = "\u{e65e}"
    static let android = "\u{e65f}"
    static let apple = "\u{e660}"

}
